### ISSUE TITLE
picom dbus service is labelled differently

### ISSUE THREAD

**Issue by Da-Boom** [yshui/picom-xrdesktop-companion#5]
picom is labelling its X display as `_0_0` in dbus -  this softwere however is searching for the string _0.0

i was able to fix this by adding another .replace('.', "_") on the end of line.

here is a diff patch of what ive done:

[dbus_name_fix.patch.zip](https://github.com/yshui/picom-xrdesktop-companion/files/9305629/dbus_name_fix.patch.zip)

**Comment by yshui** [comment]
Can you open a PR?

**Comment by Da-Boom** [comment]
Done

**Comment by yshui** [comment]
Thank you!
